<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net8.0-windows</TargetFrameworks>
    <OutputType Condition="'$(TargetFramework)' == 'net8.0-windows'">WinExe</OutputType>
    <OutputType Condition="'$(TargetFramework)' != 'net8.0-windows'">Exe</OutputType>
    <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
	<UseAppHost>true</UseAppHost>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
		<PackageReference Include="StswExpress.Analyzers" Version="*" />
	</ItemGroup>
	
	<ItemGroup>
		<ProjectReference Include="..\\StswExpress.Avalonia\\StswExpress.Avalonia.csproj" />
	</ItemGroup>
	
	<ItemGroup>
	  <AvaloniaResource Include="Assets\icon.ico" />
	</ItemGroup>
	
	<ItemGroup>
	  <Folder Include="Modules\Controls\" />
	</ItemGroup>

</Project>
