<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifiers>win-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
	<UseAppHost>true</UseAppHost>
	<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>TestApp</AssemblyName>
	<Version>1.0.0</Version>
	<Authors>Karol Staszewski</Authors>
	<GeneratePackageOnBuild>False</GeneratePackageOnBuild>
	<PackageProjectUrl>https://github.com/stsw133/StswExpress</PackageProjectUrl>
	<RepositoryUrl>https://github.com/stsw133/StswExpress</RepositoryUrl>
	<ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

	<PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
		<OutputType>WinExe</OutputType>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="Assets\icon.ico" />
	</ItemGroup>

	<ItemGroup>
    <AvaloniaXaml Remove="Modules\Controls\Typography\StswIcon\ControlsBase.axaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\icon.ico" />
  </ItemGroup>

	<ItemGroup>
		<AvaloniaResource Include="Assets\icon.ico" />
		<None Include="..\logo.png" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="11.3.9" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.9" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.9" />
	</ItemGroup>
	
	<ItemGroup>
		<PackageReference Include="StswExpress.Analyzers" Version="*" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\StswExpress.Commons\StswExpress.Commons.csproj" />
	  <ProjectReference Include="..\StswExpress.Avalonia\StswExpress.Avalonia.csproj" />
	</ItemGroup>

</Project>
