<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <Authors>Karol Staszewski</Authors>
    <Version>0.23.0</Version>
    <RepositoryUrl>https://github.com/stsw133/StswExpress</RepositoryUrl>
    <RepositoryType></RepositoryType>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageProjectUrl>https://github.com/stsw133/StswExpress</PackageProjectUrl>
    <PackageIcon>logo.png</PackageIcon>
    <Description>This package offers:
• A variety of modern controls (inspired by WinUI 3) with enhanced styling and functionalities.
• Utilities such as commands, converters, database tools, extensions, vector geometry icons, logging system, and mail sending.
• Support for GUI scaling, multiple theme options (including light/dark modes), and app localization for different languages.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\StswExpress.Wpf.xml</DocumentationFile>
    <PackageReleaseNotes>For more details, see the changelog: https://github.com/stsw133/StswExpress/blob/main/CHANGELOG.md</PackageReleaseNotes>
    <PackageTags>Controls; Themes; Utils</PackageTags>
    <Copyright>© 2025 Karol Staszewski</Copyright>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <None Update="logo.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
	  <None Include="..\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StswExpress.Analyzers" Version="*" />
  </ItemGroup>

	<ItemGroup>
    <Resource Include="Themes\Resources\*.webp" />
    <Resource Include="Utils\Translator\Translations\*.json" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\StswExpress.Commons\StswExpress.Commons.csproj" />
	</ItemGroup>

  <ItemGroup>
	  <Page Update="**/*.xaml">
		  <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
	  </Page>
  </ItemGroup>

</Project>
