<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
	<UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <Version>0.24.0</Version>
    <Authors>Karol Staszewski</Authors>
    <PackageIcon>logo.png</PackageIcon>
    <Copyright>© 2026 Karol Staszewski</Copyright>
    <Description>This package offers:
• A variety of modern controls (inspired by WinUI 3) with enhanced styling and functionalities.
• Utilities such as commands, converters, database tools, extensions, vector geometry icons, logging system, and mail sending.
• Support for GUI scaling, multiple theme options (including light/dark modes), and app localization for different languages.</Description>
	<RepositoryUrl>https://github.com/Karol-Staszewski/StswExpress-docs</RepositoryUrl>
	<PackageProjectUrl>https://github.com/Karol-Staszewski/StswExpress-docs</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageTags>Controls; Themes; Utils</PackageTags>
	<PackageReleaseNotes>For more details, see the changelog: https://github.com/Karol-Staszewski/StswExpress-docs/blob/main/articles/changelog/index.md</PackageReleaseNotes>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\StswExpress.Wpf.xml</DocumentationFile>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
	  <None Include="..\LICENSE" Pack="true" PackagePath="\" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
	  <None Include="..\THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
	  <None Include="..\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StswExpress.Analyzers" Version="*" />
  </ItemGroup>

	<ItemGroup>
    <Resource Include="Themes\Resources\*.webp" />
    <Resource Include="Utils\Translator\Translations\*.json" />
  </ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\StswExpress.Commons\StswExpress.Commons.csproj" />
	</ItemGroup>

  <ItemGroup>
	  <Page Update="**/*.xaml">
		  <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
	  </Page>
  </ItemGroup>

</Project>
