<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Authors>Karol Staszewski</Authors>
    <Version>0.24.0</Version>
	<PackageIcon>logo.png</PackageIcon>
    <Copyright>© 2026 Karol Staszewski</Copyright>
    <Description>This package offers utilities such as:
• extended observable collections and objects
• database query tools
• simple logging system
• mail sending and configuration
• messangers and stores
• data hashing methods
• code extensions and helpers</Description>
	<RepositoryUrl>https://github.com/Karol-Staszewski/StswExpress-docs</RepositoryUrl>
	<PackageProjectUrl>https://github.com/Karol-Staszewski/StswExpress-docs</PackageProjectUrl>
	<PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageTags>Utils</PackageTags>
	<PackageReleaseNotes>For more details, see the changelog: https://github.com/Karol-Staszewski/StswExpress-docs/blob/main/articles/changelog/index.md</PackageReleaseNotes>
	<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
	<GenerateDocumentationFile>True</GenerateDocumentationFile>
	<DocumentationFile>bin\$(Configuration)\$(TargetFramework)\StswExpress.Commons.xml</DocumentationFile>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
	<CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)Generated</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>

  <ItemGroup>
	  <None Include="..\LICENSE" Pack="true" PackagePath="\" />
	  <None Include="..\README.md" Pack="true" PackagePath="\" />
	  <None Include="..\THIRD-PARTY-NOTICES.txt" Pack="true" PackagePath="\" />
	  <None Include="..\logo.png" Pack="true" PackagePath="\" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.15.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
  </ItemGroup>

</Project>
