//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StswExpress {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StswExpress.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_accept {
            get {
                object obj = ResourceManager.GetObject("icon16_accept", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_add {
            get {
                object obj = ResourceManager.GetObject("icon16_add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_admin {
            get {
                object obj = ResourceManager.GetObject("icon16_admin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_allow {
            get {
                object obj = ResourceManager.GetObject("icon16_allow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_appearance {
            get {
                object obj = ResourceManager.GetObject("icon16_appearance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_archive {
            get {
                object obj = ResourceManager.GetObject("icon16_archive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_articles {
            get {
                object obj = ResourceManager.GetObject("icon16_articles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_attachment {
            get {
                object obj = ResourceManager.GetObject("icon16_attachment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_automatic {
            get {
                object obj = ResourceManager.GetObject("icon16_automatic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_bank {
            get {
                object obj = ResourceManager.GetObject("icon16_bank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_block {
            get {
                object obj = ResourceManager.GetObject("icon16_block", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_book {
            get {
                object obj = ResourceManager.GetObject("icon16_book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_books {
            get {
                object obj = ResourceManager.GetObject("icon16_books", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_briefcase {
            get {
                object obj = ResourceManager.GetObject("icon16_briefcase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_cake {
            get {
                object obj = ResourceManager.GetObject("icon16_cake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_calendar {
            get {
                object obj = ResourceManager.GetObject("icon16_calendar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_camfile {
            get {
                object obj = ResourceManager.GetObject("icon16_camfile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_clear {
            get {
                object obj = ResourceManager.GetObject("icon16_clear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_close {
            get {
                object obj = ResourceManager.GetObject("icon16_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_code {
            get {
                object obj = ResourceManager.GetObject("icon16_code", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_coins {
            get {
                object obj = ResourceManager.GetObject("icon16_coins", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_color {
            get {
                object obj = ResourceManager.GetObject("icon16_color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_colors {
            get {
                object obj = ResourceManager.GetObject("icon16_colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_community {
            get {
                object obj = ResourceManager.GetObject("icon16_community", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_company {
            get {
                object obj = ResourceManager.GetObject("icon16_company", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_config {
            get {
                object obj = ResourceManager.GetObject("icon16_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_contacts {
            get {
                object obj = ResourceManager.GetObject("icon16_contacts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_contractors {
            get {
                object obj = ResourceManager.GetObject("icon16_contractors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_contrast {
            get {
                object obj = ResourceManager.GetObject("icon16_contrast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_copy {
            get {
                object obj = ResourceManager.GetObject("icon16_copy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_customize {
            get {
                object obj = ResourceManager.GetObject("icon16_customize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_cut {
            get {
                object obj = ResourceManager.GetObject("icon16_cut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_database {
            get {
                object obj = ResourceManager.GetObject("icon16_database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_deadline {
            get {
                object obj = ResourceManager.GetObject("icon16_deadline", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_descending {
            get {
                object obj = ResourceManager.GetObject("icon16_descending", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_documents {
            get {
                object obj = ResourceManager.GetObject("icon16_documents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_download {
            get {
                object obj = ResourceManager.GetObject("icon16_download", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_duplicate {
            get {
                object obj = ResourceManager.GetObject("icon16_duplicate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_edit {
            get {
                object obj = ResourceManager.GetObject("icon16_edit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_error {
            get {
                object obj = ResourceManager.GetObject("icon16_error", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_excel {
            get {
                object obj = ResourceManager.GetObject("icon16_excel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_export {
            get {
                object obj = ResourceManager.GetObject("icon16_export", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_female {
            get {
                object obj = ResourceManager.GetObject("icon16_female", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_filter {
            get {
                object obj = ResourceManager.GetObject("icon16_filter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_find {
            get {
                object obj = ResourceManager.GetObject("icon16_find", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_black {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_blue {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_green {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_purple {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_purple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_red {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_white {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_white", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_flag_yellow {
            get {
                object obj = ResourceManager.GetObject("icon16_flag_yellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_folder {
            get {
                object obj = ResourceManager.GetObject("icon16_folder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_font {
            get {
                object obj = ResourceManager.GetObject("icon16_font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_food {
            get {
                object obj = ResourceManager.GetObject("icon16_food", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_fullscreen {
            get {
                object obj = ResourceManager.GetObject("icon16_fullscreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_gallery {
            get {
                object obj = ResourceManager.GetObject("icon16_gallery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_global {
            get {
                object obj = ResourceManager.GetObject("icon16_global", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_greetings {
            get {
                object obj = ResourceManager.GetObject("icon16_greetings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_grid {
            get {
                object obj = ResourceManager.GetObject("icon16_grid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_groups {
            get {
                object obj = ResourceManager.GetObject("icon16_groups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_half {
            get {
                object obj = ResourceManager.GetObject("icon16_half", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_hand {
            get {
                object obj = ResourceManager.GetObject("icon16_hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_help {
            get {
                object obj = ResourceManager.GetObject("icon16_help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_history {
            get {
                object obj = ResourceManager.GetObject("icon16_history", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_icons {
            get {
                object obj = ResourceManager.GetObject("icon16_icons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_identity {
            get {
                object obj = ResourceManager.GetObject("icon16_identity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_import {
            get {
                object obj = ResourceManager.GetObject("icon16_import", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_info {
            get {
                object obj = ResourceManager.GetObject("icon16_info", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_link {
            get {
                object obj = ResourceManager.GetObject("icon16_link", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_list {
            get {
                object obj = ResourceManager.GetObject("icon16_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_lock {
            get {
                object obj = ResourceManager.GetObject("icon16_lock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_login {
            get {
                object obj = ResourceManager.GetObject("icon16_login", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_logout {
            get {
                object obj = ResourceManager.GetObject("icon16_logout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_mail {
            get {
                object obj = ResourceManager.GetObject("icon16_mail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_male {
            get {
                object obj = ResourceManager.GetObject("icon16_male", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_message {
            get {
                object obj = ResourceManager.GetObject("icon16_message", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_misc {
            get {
                object obj = ResourceManager.GetObject("icon16_misc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_network {
            get {
                object obj = ResourceManager.GetObject("icon16_network", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_note {
            get {
                object obj = ResourceManager.GetObject("icon16_note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_notifications {
            get {
                object obj = ResourceManager.GetObject("icon16_notifications", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_openrecent {
            get {
                object obj = ResourceManager.GetObject("icon16_openrecent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_pallets {
            get {
                object obj = ResourceManager.GetObject("icon16_pallets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_paste {
            get {
                object obj = ResourceManager.GetObject("icon16_paste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_pdf {
            get {
                object obj = ResourceManager.GetObject("icon16_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_photos {
            get {
                object obj = ResourceManager.GetObject("icon16_photos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_pin {
            get {
                object obj = ResourceManager.GetObject("icon16_pin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_preferences {
            get {
                object obj = ResourceManager.GetObject("icon16_preferences", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_present {
            get {
                object obj = ResourceManager.GetObject("icon16_present", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_printer {
            get {
                object obj = ResourceManager.GetObject("icon16_printer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_profile {
            get {
                object obj = ResourceManager.GetObject("icon16_profile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_random {
            get {
                object obj = ResourceManager.GetObject("icon16_random", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_record {
            get {
                object obj = ResourceManager.GetObject("icon16_record", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_refresh {
            get {
                object obj = ResourceManager.GetObject("icon16_refresh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_remove {
            get {
                object obj = ResourceManager.GetObject("icon16_remove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_return {
            get {
                object obj = ResourceManager.GetObject("icon16_return", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_rotate_left {
            get {
                object obj = ResourceManager.GetObject("icon16_rotate_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_rotate_right {
            get {
                object obj = ResourceManager.GetObject("icon16_rotate_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_save {
            get {
                object obj = ResourceManager.GetObject("icon16_save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_saveall {
            get {
                object obj = ResourceManager.GetObject("icon16_saveall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_saveas {
            get {
                object obj = ResourceManager.GetObject("icon16_saveas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_scanner {
            get {
                object obj = ResourceManager.GetObject("icon16_scanner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_schedule {
            get {
                object obj = ResourceManager.GetObject("icon16_schedule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_script {
            get {
                object obj = ResourceManager.GetObject("icon16_script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_search {
            get {
                object obj = ResourceManager.GetObject("icon16_search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_select {
            get {
                object obj = ResourceManager.GetObject("icon16_select", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_send {
            get {
                object obj = ResourceManager.GetObject("icon16_send", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_settings {
            get {
                object obj = ResourceManager.GetObject("icon16_settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_show {
            get {
                object obj = ResourceManager.GetObject("icon16_show", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_source {
            get {
                object obj = ResourceManager.GetObject("icon16_source", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_star {
            get {
                object obj = ResourceManager.GetObject("icon16_star", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_stats {
            get {
                object obj = ResourceManager.GetObject("icon16_stats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_switch {
            get {
                object obj = ResourceManager.GetObject("icon16_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_system {
            get {
                object obj = ResourceManager.GetObject("icon16_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_tag {
            get {
                object obj = ResourceManager.GetObject("icon16_tag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_test {
            get {
                object obj = ResourceManager.GetObject("icon16_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_timer {
            get {
                object obj = ResourceManager.GetObject("icon16_timer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_tools {
            get {
                object obj = ResourceManager.GetObject("icon16_tools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_translate {
            get {
                object obj = ResourceManager.GetObject("icon16_translate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_transport {
            get {
                object obj = ResourceManager.GetObject("icon16_transport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_trash {
            get {
                object obj = ResourceManager.GetObject("icon16_trash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_truck {
            get {
                object obj = ResourceManager.GetObject("icon16_truck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_txt {
            get {
                object obj = ResourceManager.GetObject("icon16_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_unlock {
            get {
                object obj = ResourceManager.GetObject("icon16_unlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_upgrade {
            get {
                object obj = ResourceManager.GetObject("icon16_upgrade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_upload {
            get {
                object obj = ResourceManager.GetObject("icon16_upload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_user {
            get {
                object obj = ResourceManager.GetObject("icon16_user", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_users {
            get {
                object obj = ResourceManager.GetObject("icon16_users", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_versions {
            get {
                object obj = ResourceManager.GetObject("icon16_versions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_wait {
            get {
                object obj = ResourceManager.GetObject("icon16_wait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_warehouse {
            get {
                object obj = ResourceManager.GetObject("icon16_warehouse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_xlsx {
            get {
                object obj = ResourceManager.GetObject("icon16_xlsx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon16_xml {
            get {
                object obj = ResourceManager.GetObject("icon16_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_between {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_between", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_contains {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_contains", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_endswith {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_endswith", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_equal {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_equal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_greater {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_greater", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_greaterequal {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_greaterequal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_in {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_in", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_less {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_less", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_lessequal {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_lessequal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_like {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_like", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_notcontains {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_notcontains", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_notequal {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_notequal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_notin {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_notin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_notlike {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_notlike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_notnull {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_notnull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_null {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_null", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon20_filter_startswith {
            get {
                object obj = ResourceManager.GetObject("icon20_filter_startswith", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_accept {
            get {
                object obj = ResourceManager.GetObject("icon32_accept", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_add {
            get {
                object obj = ResourceManager.GetObject("icon32_add", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_admin {
            get {
                object obj = ResourceManager.GetObject("icon32_admin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_allow {
            get {
                object obj = ResourceManager.GetObject("icon32_allow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_appearance {
            get {
                object obj = ResourceManager.GetObject("icon32_appearance", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_archive {
            get {
                object obj = ResourceManager.GetObject("icon32_archive", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_articles {
            get {
                object obj = ResourceManager.GetObject("icon32_articles", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_attachment {
            get {
                object obj = ResourceManager.GetObject("icon32_attachment", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_automatic {
            get {
                object obj = ResourceManager.GetObject("icon32_automatic", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_bank {
            get {
                object obj = ResourceManager.GetObject("icon32_bank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_block {
            get {
                object obj = ResourceManager.GetObject("icon32_block", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_book {
            get {
                object obj = ResourceManager.GetObject("icon32_book", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_books {
            get {
                object obj = ResourceManager.GetObject("icon32_books", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_briefcase {
            get {
                object obj = ResourceManager.GetObject("icon32_briefcase", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_cake {
            get {
                object obj = ResourceManager.GetObject("icon32_cake", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_calendar {
            get {
                object obj = ResourceManager.GetObject("icon32_calendar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_camfile {
            get {
                object obj = ResourceManager.GetObject("icon32_camfile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_clear {
            get {
                object obj = ResourceManager.GetObject("icon32_clear", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_close {
            get {
                object obj = ResourceManager.GetObject("icon32_close", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_code {
            get {
                object obj = ResourceManager.GetObject("icon32_code", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_coins {
            get {
                object obj = ResourceManager.GetObject("icon32_coins", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_color {
            get {
                object obj = ResourceManager.GetObject("icon32_color", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_colors {
            get {
                object obj = ResourceManager.GetObject("icon32_colors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_community {
            get {
                object obj = ResourceManager.GetObject("icon32_community", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_company {
            get {
                object obj = ResourceManager.GetObject("icon32_company", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_config {
            get {
                object obj = ResourceManager.GetObject("icon32_config", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_contacts {
            get {
                object obj = ResourceManager.GetObject("icon32_contacts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_contractors {
            get {
                object obj = ResourceManager.GetObject("icon32_contractors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_contrast {
            get {
                object obj = ResourceManager.GetObject("icon32_contrast", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_copy {
            get {
                object obj = ResourceManager.GetObject("icon32_copy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_customize {
            get {
                object obj = ResourceManager.GetObject("icon32_customize", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_cut {
            get {
                object obj = ResourceManager.GetObject("icon32_cut", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_database {
            get {
                object obj = ResourceManager.GetObject("icon32_database", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_deadline {
            get {
                object obj = ResourceManager.GetObject("icon32_deadline", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_descending {
            get {
                object obj = ResourceManager.GetObject("icon32_descending", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_documents {
            get {
                object obj = ResourceManager.GetObject("icon32_documents", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_download {
            get {
                object obj = ResourceManager.GetObject("icon32_download", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_duplicate {
            get {
                object obj = ResourceManager.GetObject("icon32_duplicate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_edit {
            get {
                object obj = ResourceManager.GetObject("icon32_edit", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_error {
            get {
                object obj = ResourceManager.GetObject("icon32_error", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_excel {
            get {
                object obj = ResourceManager.GetObject("icon32_excel", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_export {
            get {
                object obj = ResourceManager.GetObject("icon32_export", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_female {
            get {
                object obj = ResourceManager.GetObject("icon32_female", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_filter {
            get {
                object obj = ResourceManager.GetObject("icon32_filter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_find {
            get {
                object obj = ResourceManager.GetObject("icon32_find", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_black {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_black", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_blue {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_blue", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_green {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_green", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_purple {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_purple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_red {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_red", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_white {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_white", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_flag_yellow {
            get {
                object obj = ResourceManager.GetObject("icon32_flag_yellow", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_folder {
            get {
                object obj = ResourceManager.GetObject("icon32_folder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_font {
            get {
                object obj = ResourceManager.GetObject("icon32_font", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_food {
            get {
                object obj = ResourceManager.GetObject("icon32_food", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_fullscreen {
            get {
                object obj = ResourceManager.GetObject("icon32_fullscreen", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_gallery {
            get {
                object obj = ResourceManager.GetObject("icon32_gallery", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_global {
            get {
                object obj = ResourceManager.GetObject("icon32_global", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_greetings {
            get {
                object obj = ResourceManager.GetObject("icon32_greetings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_grid {
            get {
                object obj = ResourceManager.GetObject("icon32_grid", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_groups {
            get {
                object obj = ResourceManager.GetObject("icon32_groups", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_half {
            get {
                object obj = ResourceManager.GetObject("icon32_half", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_hand {
            get {
                object obj = ResourceManager.GetObject("icon32_hand", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_help {
            get {
                object obj = ResourceManager.GetObject("icon32_help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_history {
            get {
                object obj = ResourceManager.GetObject("icon32_history", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_icons {
            get {
                object obj = ResourceManager.GetObject("icon32_icons", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_identity {
            get {
                object obj = ResourceManager.GetObject("icon32_identity", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_import {
            get {
                object obj = ResourceManager.GetObject("icon32_import", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_info {
            get {
                object obj = ResourceManager.GetObject("icon32_info", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_link {
            get {
                object obj = ResourceManager.GetObject("icon32_link", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_list {
            get {
                object obj = ResourceManager.GetObject("icon32_list", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_lock {
            get {
                object obj = ResourceManager.GetObject("icon32_lock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_log {
            get {
                object obj = ResourceManager.GetObject("icon32_log", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_login {
            get {
                object obj = ResourceManager.GetObject("icon32_login", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_logout {
            get {
                object obj = ResourceManager.GetObject("icon32_logout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_mail {
            get {
                object obj = ResourceManager.GetObject("icon32_mail", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_male {
            get {
                object obj = ResourceManager.GetObject("icon32_male", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_message {
            get {
                object obj = ResourceManager.GetObject("icon32_message", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_misc {
            get {
                object obj = ResourceManager.GetObject("icon32_misc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_network {
            get {
                object obj = ResourceManager.GetObject("icon32_network", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_note {
            get {
                object obj = ResourceManager.GetObject("icon32_note", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_notifications {
            get {
                object obj = ResourceManager.GetObject("icon32_notifications", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_openrecent {
            get {
                object obj = ResourceManager.GetObject("icon32_openrecent", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_pallets {
            get {
                object obj = ResourceManager.GetObject("icon32_pallets", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_paste {
            get {
                object obj = ResourceManager.GetObject("icon32_paste", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_pdf {
            get {
                object obj = ResourceManager.GetObject("icon32_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_people {
            get {
                object obj = ResourceManager.GetObject("icon32_people", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_photos {
            get {
                object obj = ResourceManager.GetObject("icon32_photos", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_pin {
            get {
                object obj = ResourceManager.GetObject("icon32_pin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_preferences {
            get {
                object obj = ResourceManager.GetObject("icon32_preferences", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_present {
            get {
                object obj = ResourceManager.GetObject("icon32_present", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_printer {
            get {
                object obj = ResourceManager.GetObject("icon32_printer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_profile {
            get {
                object obj = ResourceManager.GetObject("icon32_profile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_random {
            get {
                object obj = ResourceManager.GetObject("icon32_random", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_record {
            get {
                object obj = ResourceManager.GetObject("icon32_record", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_refresh {
            get {
                object obj = ResourceManager.GetObject("icon32_refresh", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_remove {
            get {
                object obj = ResourceManager.GetObject("icon32_remove", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_return {
            get {
                object obj = ResourceManager.GetObject("icon32_return", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_rotate_left {
            get {
                object obj = ResourceManager.GetObject("icon32_rotate_left", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_rotate_right {
            get {
                object obj = ResourceManager.GetObject("icon32_rotate_right", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_save {
            get {
                object obj = ResourceManager.GetObject("icon32_save", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_saveall {
            get {
                object obj = ResourceManager.GetObject("icon32_saveall", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_saveas {
            get {
                object obj = ResourceManager.GetObject("icon32_saveas", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_scanner {
            get {
                object obj = ResourceManager.GetObject("icon32_scanner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_schedule {
            get {
                object obj = ResourceManager.GetObject("icon32_schedule", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_script {
            get {
                object obj = ResourceManager.GetObject("icon32_script", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_search {
            get {
                object obj = ResourceManager.GetObject("icon32_search", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_select {
            get {
                object obj = ResourceManager.GetObject("icon32_select", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_send {
            get {
                object obj = ResourceManager.GetObject("icon32_send", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_settings {
            get {
                object obj = ResourceManager.GetObject("icon32_settings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_show {
            get {
                object obj = ResourceManager.GetObject("icon32_show", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_source {
            get {
                object obj = ResourceManager.GetObject("icon32_source", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_star {
            get {
                object obj = ResourceManager.GetObject("icon32_star", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_stats {
            get {
                object obj = ResourceManager.GetObject("icon32_stats", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_switch {
            get {
                object obj = ResourceManager.GetObject("icon32_switch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_system {
            get {
                object obj = ResourceManager.GetObject("icon32_system", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_tag {
            get {
                object obj = ResourceManager.GetObject("icon32_tag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_test {
            get {
                object obj = ResourceManager.GetObject("icon32_test", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_timer {
            get {
                object obj = ResourceManager.GetObject("icon32_timer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_tools {
            get {
                object obj = ResourceManager.GetObject("icon32_tools", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_translate {
            get {
                object obj = ResourceManager.GetObject("icon32_translate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_transport {
            get {
                object obj = ResourceManager.GetObject("icon32_transport", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_trash {
            get {
                object obj = ResourceManager.GetObject("icon32_trash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_truck {
            get {
                object obj = ResourceManager.GetObject("icon32_truck", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_txt {
            get {
                object obj = ResourceManager.GetObject("icon32_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_unlock {
            get {
                object obj = ResourceManager.GetObject("icon32_unlock", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_upgrade {
            get {
                object obj = ResourceManager.GetObject("icon32_upgrade", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_upload {
            get {
                object obj = ResourceManager.GetObject("icon32_upload", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_user {
            get {
                object obj = ResourceManager.GetObject("icon32_user", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_users {
            get {
                object obj = ResourceManager.GetObject("icon32_users", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_versions {
            get {
                object obj = ResourceManager.GetObject("icon32_versions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_wait {
            get {
                object obj = ResourceManager.GetObject("icon32_wait", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_warehouse {
            get {
                object obj = ResourceManager.GetObject("icon32_warehouse", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_xlsx {
            get {
                object obj = ResourceManager.GetObject("icon32_xlsx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] icon32_xml {
            get {
                object obj = ResourceManager.GetObject("icon32_xml", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
