//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StswExpress {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    public sealed partial class Themes : global::System.Configuration.ApplicationSettingsBase {
        
        private static Themes defaultInstance = ((Themes)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Themes())));
        
        public static Themes Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Theme {
            get {
                return ((int)(this["Theme"]));
            }
            set {
                this["Theme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EEE")]
        public string cTitleBarBackground {
            get {
                return ((string)(this["cTitleBarBackground"]));
            }
            set {
                this["cTitleBarBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#CCC")]
        public string cTitleBarBorder {
            get {
                return ((string)(this["cTitleBarBorder"]));
            }
            set {
                this["cTitleBarBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000")]
        public string cTitleBarForeground1 {
            get {
                return ((string)(this["cTitleBarForeground1"]));
            }
            set {
                this["cTitleBarForeground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#555")]
        public string cTitleBarForeground2 {
            get {
                return ((string)(this["cTitleBarForeground2"]));
            }
            set {
                this["cTitleBarForeground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cWindowBackground {
            get {
                return ((string)(this["cWindowBackground"]));
            }
            set {
                this["cWindowBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000")]
        public string cWindowForeground {
            get {
                return ((string)(this["cWindowForeground"]));
            }
            set {
                this["cWindowForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cOptionMarkStaticBackground {
            get {
                return ((string)(this["cOptionMarkStaticBackground"]));
            }
            set {
                this["cOptionMarkStaticBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#707070")]
        public string cOptionMarkStaticBorder {
            get {
                return ((string)(this["cOptionMarkStaticBorder"]));
            }
            set {
                this["cOptionMarkStaticBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#212121")]
        public string cOptionMarkStaticGlyph {
            get {
                return ((string)(this["cOptionMarkStaticGlyph"]));
            }
            set {
                this["cOptionMarkStaticGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F3F9FF")]
        public string cOptionMarkMouseOverBackground {
            get {
                return ((string)(this["cOptionMarkMouseOverBackground"]));
            }
            set {
                this["cOptionMarkMouseOverBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#5593FF")]
        public string cOptionMarkMouseOverBorder {
            get {
                return ((string)(this["cOptionMarkMouseOverBorder"]));
            }
            set {
                this["cOptionMarkMouseOverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#212121")]
        public string cOptionMarkMouseOverGlyph {
            get {
                return ((string)(this["cOptionMarkMouseOverGlyph"]));
            }
            set {
                this["cOptionMarkMouseOverGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D9ECFF")]
        public string cOptionMarkPressedBackground {
            get {
                return ((string)(this["cOptionMarkPressedBackground"]));
            }
            set {
                this["cOptionMarkPressedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3C77DD")]
        public string cOptionMarkPressedBorder {
            get {
                return ((string)(this["cOptionMarkPressedBorder"]));
            }
            set {
                this["cOptionMarkPressedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#212121")]
        public string cOptionMarkPressedGlyph {
            get {
                return ((string)(this["cOptionMarkPressedGlyph"]));
            }
            set {
                this["cOptionMarkPressedGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E6E6E6")]
        public string cOptionMarkDisabledBackground {
            get {
                return ((string)(this["cOptionMarkDisabledBackground"]));
            }
            set {
                this["cOptionMarkDisabledBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BCBCBC")]
        public string cOptionMarkDisabledBorder {
            get {
                return ((string)(this["cOptionMarkDisabledBorder"]));
            }
            set {
                this["cOptionMarkDisabledBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#707070")]
        public string cOptionMarkDisabledGlyph {
            get {
                return ((string)(this["cOptionMarkDisabledGlyph"]));
            }
            set {
                this["cOptionMarkDisabledGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#888")]
        public string cDisabledForeground {
            get {
                return ((string)(this["cDisabledForeground"]));
            }
            set {
                this["cDisabledForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string cComboBoxStaticBackground1 {
            get {
                return ((string)(this["cComboBoxStaticBackground1"]));
            }
            set {
                this["cComboBoxStaticBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E5E5E5")]
        public string cComboBoxStaticBackground2 {
            get {
                return ((string)(this["cComboBoxStaticBackground2"]));
            }
            set {
                this["cComboBoxStaticBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ACACAC")]
        public string cComboBoxStaticBorder {
            get {
                return ((string)(this["cComboBoxStaticBorder"]));
            }
            set {
                this["cComboBoxStaticBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#606060")]
        public string cComboBoxStaticGlyph {
            get {
                return ((string)(this["cComboBoxStaticGlyph"]));
            }
            set {
                this["cComboBoxStaticGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cComboBoxStaticEditableBackground {
            get {
                return ((string)(this["cComboBoxStaticEditableBackground"]));
            }
            set {
                this["cComboBoxStaticEditableBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ABADB3")]
        public string cComboBoxStaticEditableBorder {
            get {
                return ((string)(this["cComboBoxStaticEditableBorder"]));
            }
            set {
                this["cComboBoxStaticEditableBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ECF4FC")]
        public string cComboBoxMouseOverBackground1 {
            get {
                return ((string)(this["cComboBoxMouseOverBackground1"]));
            }
            set {
                this["cComboBoxMouseOverBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DCECFC")]
        public string cComboBoxMouseOverBackground2 {
            get {
                return ((string)(this["cComboBoxMouseOverBackground2"]));
            }
            set {
                this["cComboBoxMouseOverBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7EB4EA")]
        public string cComboBoxMouseOverBorder {
            get {
                return ((string)(this["cComboBoxMouseOverBorder"]));
            }
            set {
                this["cComboBoxMouseOverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000")]
        public string cComboBoxMouseOverGlyph {
            get {
                return ((string)(this["cComboBoxMouseOverGlyph"]));
            }
            set {
                this["cComboBoxMouseOverGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cComboBoxMouseOverEditableBackground {
            get {
                return ((string)(this["cComboBoxMouseOverEditableBackground"]));
            }
            set {
                this["cComboBoxMouseOverEditableBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7EB4EA")]
        public string cComboBoxMouseOverEditableBorder {
            get {
                return ((string)(this["cComboBoxMouseOverEditableBorder"]));
            }
            set {
                this["cComboBoxMouseOverEditableBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#EBF4FC")]
        public string cComboBoxMouseOverEditableButtonBackground1 {
            get {
                return ((string)(this["cComboBoxMouseOverEditableButtonBackground1"]));
            }
            set {
                this["cComboBoxMouseOverEditableButtonBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DCECFC")]
        public string cComboBoxMouseOverEditableButtonBackground2 {
            get {
                return ((string)(this["cComboBoxMouseOverEditableButtonBackground2"]));
            }
            set {
                this["cComboBoxMouseOverEditableButtonBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7EB4EA")]
        public string cComboBoxMouseOverEditableButtonBorder {
            get {
                return ((string)(this["cComboBoxMouseOverEditableButtonBorder"]));
            }
            set {
                this["cComboBoxMouseOverEditableButtonBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DAECFC")]
        public string cComboBoxPressedBackground1 {
            get {
                return ((string)(this["cComboBoxPressedBackground1"]));
            }
            set {
                this["cComboBoxPressedBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#C4E0FC")]
        public string cComboBoxPressedBackground2 {
            get {
                return ((string)(this["cComboBoxPressedBackground2"]));
            }
            set {
                this["cComboBoxPressedBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#569DE5")]
        public string cComboBoxPressedBorder {
            get {
                return ((string)(this["cComboBoxPressedBorder"]));
            }
            set {
                this["cComboBoxPressedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000")]
        public string cComboBoxPressedGlyph {
            get {
                return ((string)(this["cComboBoxPressedGlyph"]));
            }
            set {
                this["cComboBoxPressedGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cComboBoxPressedEditableBackground {
            get {
                return ((string)(this["cComboBoxPressedEditableBackground"]));
            }
            set {
                this["cComboBoxPressedEditableBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#569DE5")]
        public string cComboBoxPressedEditableBorder {
            get {
                return ((string)(this["cComboBoxPressedEditableBorder"]));
            }
            set {
                this["cComboBoxPressedEditableBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DAEBFC")]
        public string cComboBoxPressedEditableButtonBackground1 {
            get {
                return ((string)(this["cComboBoxPressedEditableButtonBackground1"]));
            }
            set {
                this["cComboBoxPressedEditableButtonBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#C4E0FC")]
        public string cComboBoxPressedEditableButtonBackground2 {
            get {
                return ((string)(this["cComboBoxPressedEditableButtonBackground2"]));
            }
            set {
                this["cComboBoxPressedEditableButtonBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#569DE5")]
        public string cComboBoxPressedEditableButtonBorder {
            get {
                return ((string)(this["cComboBoxPressedEditableButtonBorder"]));
            }
            set {
                this["cComboBoxPressedEditableButtonBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string cComboBoxDisabledBackground {
            get {
                return ((string)(this["cComboBoxDisabledBackground"]));
            }
            set {
                this["cComboBoxDisabledBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D9D9D9")]
        public string cComboBoxDisabledBorder {
            get {
                return ((string)(this["cComboBoxDisabledBorder"]));
            }
            set {
                this["cComboBoxDisabledBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BFBFBF")]
        public string cComboBoxDisabledGlyph {
            get {
                return ((string)(this["cComboBoxDisabledGlyph"]));
            }
            set {
                this["cComboBoxDisabledGlyph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cComboBoxDisabledEditableBackground {
            get {
                return ((string)(this["cComboBoxDisabledEditableBackground"]));
            }
            set {
                this["cComboBoxDisabledEditableBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BFBFBF")]
        public string cComboBoxDisabledEditableBorder {
            get {
                return ((string)(this["cComboBoxDisabledEditableBorder"]));
            }
            set {
                this["cComboBoxDisabledEditableBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#1F26A0DA")]
        public string cComboBoxItemItemsviewHoverBackground {
            get {
                return ((string)(this["cComboBoxItemItemsviewHoverBackground"]));
            }
            set {
                this["cComboBoxItemItemsviewHoverBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#A826A0DA")]
        public string cComboBoxItemItemsviewHoverBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewHoverBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewHoverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3D26A0DA")]
        public string cComboBoxItemItemsviewSelectedBackground {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedBackground"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26A0DA")]
        public string cComboBoxItemItemsviewSelectedBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2E0080FF")]
        public string cComboBoxItemItemsviewSelectedHoverBackground {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedHoverBackground"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedHoverBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99006CD9")]
        public string cComboBoxItemItemsviewSelectedHoverBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedHoverBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedHoverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3DDADADA")]
        public string cComboBoxItemItemsviewSelectedNoFocusBackground {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedNoFocusBackground"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedNoFocusBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DADADA")]
        public string cComboBoxItemItemsviewSelectedNoFocusBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewSelectedNoFocusBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewSelectedNoFocusBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26A0DA")]
        public string cComboBoxItemItemsviewFocusBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewFocusBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewFocusBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#5426A0DA")]
        public string cComboBoxItemItemsviewHoverFocusBackground {
            get {
                return ((string)(this["cComboBoxItemItemsviewHoverFocusBackground"]));
            }
            set {
                this["cComboBoxItemItemsviewHoverFocusBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26A0DA")]
        public string cComboBoxItemItemsviewHoverFocusBorder {
            get {
                return ((string)(this["cComboBoxItemItemsviewHoverFocusBorder"]));
            }
            set {
                this["cComboBoxItemItemsviewHoverFocusBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DDD")]
        public string cButtonStaticBackground {
            get {
                return ((string)(this["cButtonStaticBackground"]));
            }
            set {
                this["cButtonStaticBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#707070")]
        public string cButtonStaticBorder {
            get {
                return ((string)(this["cButtonStaticBorder"]));
            }
            set {
                this["cButtonStaticBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#BEE6FD")]
        public string cButtonMouseOverBackground {
            get {
                return ((string)(this["cButtonMouseOverBackground"]));
            }
            set {
                this["cButtonMouseOverBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3C7FB1")]
        public string cButtonMouseOverBorder {
            get {
                return ((string)(this["cButtonMouseOverBorder"]));
            }
            set {
                this["cButtonMouseOverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#C4E5F6")]
        public string cButtonPressedBackground {
            get {
                return ((string)(this["cButtonPressedBackground"]));
            }
            set {
                this["cButtonPressedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2C628B")]
        public string cButtonPressedBorder {
            get {
                return ((string)(this["cButtonPressedBorder"]));
            }
            set {
                this["cButtonPressedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F4F4F4")]
        public string cButtonDisabledBackground {
            get {
                return ((string)(this["cButtonDisabledBackground"]));
            }
            set {
                this["cButtonDisabledBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ADB2B5")]
        public string cButtonDisabledBorder {
            get {
                return ((string)(this["cButtonDisabledBorder"]));
            }
            set {
                this["cButtonDisabledBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#838383")]
        public string cButtonDisabledForeground {
            get {
                return ((string)(this["cButtonDisabledForeground"]));
            }
            set {
                this["cButtonDisabledForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cTabItemSelectedBackground {
            get {
                return ((string)(this["cTabItemSelectedBackground"]));
            }
            set {
                this["cTabItemSelectedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ACACAC")]
        public string cTabItemSelectedBorder {
            get {
                return ((string)(this["cTabItemSelectedBorder"]));
            }
            set {
                this["cTabItemSelectedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string cTabItemStaticBackground1 {
            get {
                return ((string)(this["cTabItemStaticBackground1"]));
            }
            set {
                this["cTabItemStaticBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E5E5E5")]
        public string cTabItemStaticBackground2 {
            get {
                return ((string)(this["cTabItemStaticBackground2"]));
            }
            set {
                this["cTabItemStaticBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ACACAC")]
        public string cTabItemStaticBorder {
            get {
                return ((string)(this["cTabItemStaticBorder"]));
            }
            set {
                this["cTabItemStaticBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ECF4FC")]
        public string cTabItemMouseOverBackground1 {
            get {
                return ((string)(this["cTabItemMouseOverBackground1"]));
            }
            set {
                this["cTabItemMouseOverBackground1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DCECFC")]
        public string cTabItemMouseOverBackground2 {
            get {
                return ((string)(this["cTabItemMouseOverBackground2"]));
            }
            set {
                this["cTabItemMouseOverBackground2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#7EB4EA")]
        public string cTabItemMouseOverBorder {
            get {
                return ((string)(this["cTabItemMouseOverBorder"]));
            }
            set {
                this["cTabItemMouseOverBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string cTabItemDisabledBackground {
            get {
                return ((string)(this["cTabItemDisabledBackground"]));
            }
            set {
                this["cTabItemDisabledBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D9D9D9")]
        public string cTabItemDisabledBorder {
            get {
                return ((string)(this["cTabItemDisabledBorder"]));
            }
            set {
                this["cTabItemDisabledBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F0F0F0")]
        public string cMenuStaticBackground {
            get {
                return ((string)(this["cMenuStaticBackground"]));
            }
            set {
                this["cMenuStaticBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#999")]
        public string cMenuStaticBorder {
            get {
                return ((string)(this["cMenuStaticBorder"]));
            }
            set {
                this["cMenuStaticBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#212121")]
        public string cMenuStaticForeground {
            get {
                return ((string)(this["cMenuStaticForeground"]));
            }
            set {
                this["cMenuStaticForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#D7D7D7")]
        public string cMenuStaticSeparator {
            get {
                return ((string)(this["cMenuStaticSeparator"]));
            }
            set {
                this["cMenuStaticSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#707070")]
        public string cMenuDisabledForeground {
            get {
                return ((string)(this["cMenuDisabledForeground"]));
            }
            set {
                this["cMenuDisabledForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3D26A0DA")]
        public string cMenuItemSelectedBackground {
            get {
                return ((string)(this["cMenuItemSelectedBackground"]));
            }
            set {
                this["cMenuItemSelectedBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26A0DA")]
        public string cMenuItemSelectedBorder {
            get {
                return ((string)(this["cMenuItemSelectedBorder"]));
            }
            set {
                this["cMenuItemSelectedBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#3D26A0DA")]
        public string cMenuItemHighlightBackground {
            get {
                return ((string)(this["cMenuItemHighlightBackground"]));
            }
            set {
                this["cMenuItemHighlightBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#26A0DA")]
        public string cMenuItemHighlightBorder {
            get {
                return ((string)(this["cMenuItemHighlightBorder"]));
            }
            set {
                this["cMenuItemHighlightBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#0A000000")]
        public string cMenuItemHighlightDisabledBackground {
            get {
                return ((string)(this["cMenuItemHighlightDisabledBackground"]));
            }
            set {
                this["cMenuItemHighlightDisabledBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#21000000")]
        public string cMenuItemHighlightDisabledBorder {
            get {
                return ((string)(this["cMenuItemHighlightDisabledBorder"]));
            }
            set {
                this["cMenuItemHighlightDisabledBorder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#99C1E2")]
        public string cDatePickerTextBoxMouseOverWatermark {
            get {
                return ((string)(this["cDatePickerTextBoxMouseOverWatermark"]));
            }
            set {
                this["cDatePickerTextBoxMouseOverWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cDatePickerTextBoxStaticBorderWatermark {
            get {
                return ((string)(this["cDatePickerTextBoxStaticBorderWatermark"]));
            }
            set {
                this["cDatePickerTextBoxStaticBorderWatermark"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#45D6FA")]
        public string cDatePickerTextBoxStaticBorderHost {
            get {
                return ((string)(this["cDatePickerTextBoxStaticBorderHost"]));
            }
            set {
                this["cDatePickerTextBoxStaticBorderHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2222")]
        public string cDataGridStaticGridLines {
            get {
                return ((string)(this["cDataGridStaticGridLines"]));
            }
            set {
                this["cDataGridStaticGridLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF")]
        public string cDataGridStaticBackground {
            get {
                return ((string)(this["cDataGridStaticBackground"]));
            }
            set {
                this["cDataGridStaticBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F00")]
        public string cDataGridErrorForeground {
            get {
                return ((string)(this["cDataGridErrorForeground"]));
            }
            set {
                this["cDataGridErrorForeground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#DA7")]
        public string cMain {
            get {
                return ((string)(this["cMain"]));
            }
            set {
                this["cMain"] = value;
            }
        }
    }
}
