<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>0.23.0</Version>
    <Authors>Karol Staszewski</Authors>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StswExpress.Commons\StswExpress.Commons.csproj" />
  </ItemGroup>

</Project>
